# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClie', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=60)),
                ('diasBlo', models.IntegerField()),
                ('datVen', models.DateField()),
                ('datCad', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Receber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDocto', models.CharField(max_length=10)),
                ('datEmi', models.DateField()),
                ('datVen', models.DateField()),
                ('valDocto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datPag', models.DateField()),
                ('valJuro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valDesc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valPago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codClie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
            options={
                'verbose_name': 'Receber',
                'verbose_name_plural': 'Receber',
            },
        ),
    ]
