# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receber',
            new_name='Duplicata',
        ),
        migrations.AlterModelOptions(
            name='duplicata',
            options={'verbose_name': 'Duplicata', 'verbose_name_plural': 'Duplicatas'},
        ),
    ]
