# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_duplicata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=True, verbose_name='Bloqueado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duplicata',
            name='datEmi',
            field=models.DateField(verbose_name='Dt. Emi.'),
        ),
        migrations.AlterField(
            model_name='duplicata',
            name='datPag',
            field=models.DateField(verbose_name='Dt. Pag.'),
        ),
        migrations.AlterField(
            model_name='duplicata',
            name='datVen',
            field=models.DateField(verbose_name='Dt. Ven.'),
        ),
        migrations.AlterField(
            model_name='duplicata',
            name='numDocto',
            field=models.CharField(max_length=10, verbose_name='N\xba Doct'),
        ),
        migrations.AlterField(
            model_name='duplicata',
            name='valDesc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Desc. R$'),
        ),
        migrations.AlterField(
            model_name='duplicata',
            name='valDocto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor R$'),
        ),
        migrations.AlterField(
            model_name='duplicata',
            name='valJuro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Juros R$'),
        ),
        migrations.AlterField(
            model_name='duplicata',
            name='valPago',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago R$'),
        ),
    ]
