# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20170525_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
