# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20170608_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
            preserve_default=False,
        ),
    ]
