# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicata',
            name='codClie',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='datVen',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='diasBlo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mesDesb',
        ),
        migrations.AddField(
            model_name='cliente',
            name='datPag',
            field=models.DateField(blank=True, null=True, verbose_name='Data \xdalt. Pag.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='diaVen',
            field=models.IntegerField(default=10, verbose_name='Dia Vencimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='datDesb',
            field=models.DateField(verbose_name='\xdaltimo Desbloqueio'),
        ),
        migrations.DeleteModel(
            name='Duplicata',
        ),
    ]
