# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20170609_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mesRef',
            field=models.IntegerField(default=5, verbose_name='M\xeas Refer\xeancia'),
            preserve_default=False,
        ),
    ]
